CLEAN += *.nucleo-l432kc

CFLAGS += -DSTM32L432xx

ifeq ($(DEBUG), 1)
  OPTIMIZATIONS = -Og -ggdb3
  CFLAGS += -DFREEZE_TIMER_WHEN_DEBUGGING
  BUILD_DIR_CONFIG = debug
else
  BUILD_DIR_CONFIG = release
endif

CONTIKI_TARGET_DIRS = .

CONTIKI_SOURCEFILES += platform.c

CONTIKI_CPU=$(CONTIKI)/arch/cpu/stm32l4
include $(CONTIKI_CPU)/Makefile.stm32l4